mat_files = dir('*.mat');

DATA(1,:) = {[], 'QCorrectL', 'QCorrectR', 'QL', 'QR', 'DoubleL', 'DoubleR'};

for i=1:length(mat_files)
    
    filename=mat_files(i).name;
    fprintf('%s... \n', filename);
    S = load(filename);
    
    if isfield(S, 'QLeftResponseTimes')
    [index_QLeftResponseTimes, index_QRightResponseTimes, index_QLeftResponseTimesC, index_QRightResponseTimesC, ...
        QCommandStimulusTimes, QCommandStimulusTimesC, QCommandStimulusTimesX, ...
        QLeftResponseTimes, QRightResponseTimes, QLeftResponseTimesC, QRightResponseTimesC, ...
        index_DoubleSqueezeL, index_DoubleSqueezeR] ...
        = IncludeErrorTrials(S.index_QLeftResponseTimes, S.index_QRightResponseTimes, ...
        S.QualityTrials, S.CommandStimulusTimes, S.QCommandStimulusTimes, S.Trial, S.TrialNum, ...
        S.LeftResponseTimes, S.RightResponseTimes, S.QLeftResponseTimes, S.QRightResponseTimes);
    
    fprintf('   %d/%d double squeeze trials\n', length(index_DoubleSqueezeL), length(index_DoubleSqueezeR));
    fprintf('   correct squeeze trials: (L) %d    (R) %d\n', length(QLeftResponseTimesC), length(QRightResponseTimesC));
    fprintf('   all squeeze trials:     (L) %d    (R) %d\n', length(QLeftResponseTimes), length(QRightResponseTimes));
    
    DATA(i+1,:) = { S.RecID, ...
                    length(QLeftResponseTimesC), length(QRightResponseTimesC), ...
                    length(QLeftResponseTimes), length(QRightResponseTimes), ...
                    length(index_DoubleSqueezeL), length(index_DoubleSqueezeR) };
    
    save(filename, ...
        'index_QLeftResponseTimes', 'index_QRightResponseTimes', 'index_QLeftResponseTimesC', 'index_QRightResponseTimesC', ...
        'QCommandStimulusTimes', 'QCommandStimulusTimesC', 'QCommandStimulusTimesX', ...
        'QLeftResponseTimes', 'QRightResponseTimes', 'QLeftResponseTimesC', 'QRightResponseTimesC', ...
        'index_DoubleSqueezeL', 'index_DoubleSqueezeR', ...
        '-append');
    else
        DATA{i+1,1} = S.RecID;
        fprintf('   Skipping... Quality Control not done.')
    end
  
end